### ISSUE TITLE
deleting a specific poller instance?

### ISSUE THREAD

**Issue by philjones88** [emmaguo/angular-poller#33]
Hi,

Have the scenario where I have a "parent" poller running, then when a user clicks an expand link it starts a child poller, inside a controller. When they close the child view, I want it to remove the child poller totally.

Why you ask?
I've had to add "pause" functionality (to stop Chrome issues and save us bandwidth/processing power if people leave the page/tab open by mistake in the background). And I can't use the reset method as it'd clear the parent poller.

I currently use stop() but obviously if they open + close, then tab away (it pauses pollers), then tab back the child poller still exists and starts polling again.

Is it possible to get some kind of "delete" or "delete this instance of a poller" method?

Thanks,

Phil

**Comment by emmaguo** [comment]
Thanks for the detailed explanation!:)

It seems that you only want to start the child poller the very first time user clicks on the expand link. I'm not sure if `delete` method will help you in that case. Because if you initiate the child poller inside the child controller, then everytime user clicks on the expand link, the child poller will get initiatied again.
